export default [
    
    {
        title:'应急资源管理',
        key:'/main/yjzygl',
        children:[
            {
                title:'物资储备管理',
                key:'/main/yjzygl/wzcbgl',
                children:[
                    {
                        title:'物资目录管理',
                        key:'/main/yjzygl/wzcbgl/wzmlgl',
                    },
                    {
                        title:'物资储备库点管理',
                        key:'/main/yjzygl/wzcbgl/wzcbkdgl',
                    },
                    {
                        title:'物资储备信息',
                        key:'/main/yjzygl/wzcbgl/wzcbxx',
                    }
                ]
            },
            {
                title:'设备设施管理',
                key:'/main/yjzygl/sbssgl',
            },
            {
                title:'应急组织管理',
                key:'/main/yjzygl/yjzzgl',
            },
            {
                title:'应急救援队伍',
                key:'/main/yjzygl/yjjydw',
            },
            {
                title:'应急专家',
                key:'/main/yjzygl/yjzj',
            },
            {
                title:'应急通讯录',
                key:'/main/yjzygl/yjtxl',
            }
        ]
    },
    {
        title:'应急预案',
        key:'/main/yjya'
    },
    {
        title:'应急演练',
        key:'/yjyl'
    },
    {
        title:'应急地理信息系统',
        key:'/yjdlxxxt'
    },
    {
        title:'应急事件处理',
        key:'/yjsjcl',
        children:[
            {
                title:'应急事件受理',
                key:'/main/yjsjcl/yjsjsl',
            },
            {
                title:'应急事件立案',
                key:'/main/yjsjcl/yjsjla',
            },
            {
                title:'应急事件结案',
                key:'/main/yjsjcl/yjsjja',
            }
        ]
    },
    {
        title:'应急知识库',
        key:'/yjzsk'
    }
]