export default [
    
    {
        title:'应急物资管理',
        key:'/yjwz',
        children:[
            {
                title:'物资储备管理',
                key:'/yjwz/wzcbgl',
                children:[
                    {
                        title:'物资目录管理',
                        key:'/yjwz/wzcbgl/wzmlgl',
                    },
                    {
                        title:'物资储备库点管理',
                        key:'/yjwz/wzcbgl/wzcbkdgl',
                    },
                    {
                        title:'物资储备信息',
                        key:'/yjwz/wzcbgl/wzcbxx',
                    }
                ]
            },
            {
                title:'设备设施管理',
                key:'/yjwz/sbssgl',
            },
            {
                title:'应急组织管理',
                key:'/yjwz/yjzzgl',
            },
            {
                title:'应急救援队伍',
                key:'/yjwz/yjjydw',
            },
            {
                title:'应急专家',
                key:'/yjwz/yjzj',
            },
            {
                title:'应急通讯录',
                key:'/yjwz/yjtxl',
            }
        ]
    },
    {
        title:'应急预案',
        key:'/yjya'
    },
    {
        title:'应急演练',
        key:'/yjyl'
    }
]